### ISSUE TITLE
Automate build and upload to container registry

### ISSUE THREAD

**Issue by lockejan** [mjlbach/try.nvim#1]
In the sense of "automating the boring stuff", it would be great to include some sort of Action or Pipeline which takes care of publishing new tags to the container registry.

The first thing that comes to mind is probably GH Actions, but there are other equally well suited solutions as well (e.g. Circle CI).

**Comment by mjlbach** [comment]
Definitely in favor of GHA. We should regenerate the containers each night. Shouldn't be too bad, we might create an org (maybe nvim-lsp or neovim-lsp on dockerhub)
