### ISSUE TITLE
Build nightly and tagged neovim images

### ISSUE THREAD

**Issue by lockejan** [mjlbach/try.nvim#2]
Right now it is not obvious which commit state of Neovim is included in the published images before pulling them. 

What about having image variants for tagged and nightly neovim?

I can see a quite similar possibility for the different python versions available. 

Anyway, the possibility of combinations could quickly escalate.
I'm not sure yet what could be a good starting point. 🤔

**Comment by mjlbach** [comment]
Yeah, I think we can use the alpine base multi-stage image with the latest nightly for everything. We'd want to condition CI on building/pushing that first.
